apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-grid-node-edge
  namespace: selenium-grid
  labels:
    app.kubernetes.io/name: hpa-grid-node-edge
    app.kubernetes.io/component: autoscaler
    app.kubernetes.io/part-of: selenium-grid
    app.kubernetes.io/managed-by: argocd
    browser: edge
    project: framework2026
    environment: ci
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grid-node-edge
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
