apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-firefox
  labels:
    app: selenium-firefox
spec:
  selector:
    matchLabels:
      app: selenium-firefox
  template:
    metadata:
      labels:
        app: selenium-firefox
    spec:
      containers:
        - name: selenium-firefox
          image: selenium/node-firefox:4.18.1
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_SESSIONS
              value: "1"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
