apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid-node-edge
  namespace: selenium-grid
  labels:
    app.kubernetes.io/name: grid-node-edge
    app.kubernetes.io/component: browser-node
    app.kubernetes.io/part-of: selenium-grid
    app.kubernetes.io/managed-by: argocd
    browser: edge
    project: framework2026
    environment: ci
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grid-node-edge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grid-node-edge
        app.kubernetes.io/component: browser-node
        app.kubernetes.io/part-of: selenium-grid
        browser: edge
        project: framework2026
        environment: ci
    spec:
      containers:
        - name: grid-node-edge
          image: selenium/node-edge:4.18.1
          env:
            - name: SE_EVENT_BUS_HOST
              value: "grid-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_SESSIONS
              value: "1"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - mountPath: /dev/shm
              name: shared-memory
      volumes:
        - name: shared-memory
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
